version: '3.3'

services:

   syncope:
     image: apache/syncope:2.0.9-SNAPSHOT
     ports:
       - "18080:8080"
     restart: always
     environment:
       DBMS: postgresql
       DB_URL: jdbc:postgresql://192.168.1.3:5432/syncope
       DB_USER: syncope
       DB_PASSWORD: syncope
       DB_POOL_MAX: 10
       DB_POOL_MIN: 2
       OPENJPA_REMOTE_COMMIT: sjvm
     volumes:
       - .\postgres-data:/var/lib/postgresql

   syncope-console:
     depends_on:
       - syncope
     image: apache/syncope-console:2.0.9-SNAPSHOT
     ports:
       - "28080:8080"
     restart: always
     environment:
       CORE_SCHEME: http
       CORE_HOST: syncope
       CORE_PORT: 8080

   syncope-enduser:
     depends_on:
       - syncope
     image: apache/syncope-enduser:2.0.9-SNAPSHOT
     ports:
       - "38080:8080"
     restart: always
     environment:
       CORE_SCHEME: http
       CORE_HOST: syncope
       CORE_PORT: 8080